config/routes.rb
class Subdomain
  def self.matches?(request)
    return false unless (request.subdomain.present? && request.subdomain != "www")
    return false unless request.subdomain.size.between?(1,20)    
    return true
  end
end

Belloh::Application.routes.draw do

	constraints(Subdomain) do
	  get '/', to: 'virtual_hubs#show'
	  get 'edit', to: 'virtual_hubs#edit', as: 'edit_vhub'
	  patch 'update', to: 'virtual_hubs#update', as: 'update_vhub'
	  get 'sync', to: 'hub_posts#sync'
	end

  root 'welcome#show'

  get "user/:id", to: "users#show", as: "user"
  resources :hub_posts, only: [:index,:create]
  resources :virtual_hubs, only: [:create]

  resources :posts, only: [:index,:create]
  get 'sync', to: 'posts#sync'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'about', to: "information#about"
  get 'help', to: "information#help"
  get 'terms', to: "information#terms"
  get 'privacy', to: "information#privacy"
  get 'hubs', to: "information#hubs"
  get 'usage', to: "information#usage"

  

end

app/models/virtual_hub.rb
class VirtualHub < ActiveRecord::Base
	belongs_to :admin, class_name: 'User', foreign_key: :admin_id
	has_many :posts, class_name: 'HubPost'
	
	has_attached_file :background, :size => { :in => 0..2.megabytes }#, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	has_attached_file :avatar, :styles => { :default => "300x300#" }, :size => { :in => 0..2.megabytes }
	
	validates_uniqueness_of :name
	validates_length_of :name, :minimum => 1, :maximum => 20
	validates_presence_of :admin
	
	before_save do self.name.downcase! end
end

app/controllers/virtual_hubs_controller.rb
class VirtualHubsController < ApplicationController
	before_action :authenticate_user!, except: [:show]
  before_action :set_vhub, except: [:show,:create]
	
  def show
	  @vhub = VirtualHub.where(name: request.subdomain).first
	  if @vhub.nil?
	    @virtual_hub = VirtualHub.new
	    @virtual_hub.name = request.subdomain
	  else
	    @hub_post = HubPost.new
	    @hub_post.virtual_hub = @vhub
	    setup_posts(@vhub.posts)
	    @background = @vhub.background
	    @avatar = @vhub.avatar
	    session[:vhub_id] = @vhub.id
    end
  end

  def create
    @virtual_hub = current_user.virtual_hubs.build(virtual_hub_params)
    respond_to do |format|
      if @virtual_hub.save
	      format.html { redirect_to root_path }
      else
        format.html { render action: 'show' }
      end
    end
  end

  def edit
	end
	
	def update
	  respond_to do |format|
      if @vhub.update(vhub_params)
	      format.html { redirect_to root_path }
      else
        format.html { render action: 'edit' }
      end
    end
	end
	
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def virtual_hub_params
    params.require(:virtual_hub).permit(:name)
  end

  def vhub_params
    params.require(:virtual_hub).permit(:description, :background, :avatar)
  end

  def set_vhub
	  @vhub = VirtualHub.where(name: request.subdomain).first
	  redirect_to root_path if @vhub.nil?
	end
end

app/helpers/virtual_hub_helper.rb
module VirtualHubHelper
end

app/views/virtual_hubs/_errors.html.erb
<% if vhub.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(vhub.errors.count, "error") %> prohibited this virtual hub from being saved:</h2>
    <ul>
    <% vhub.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/virtual_hubs/_form.html.erb
<%= form_for(@virtual_hub) do |f| %>
  <%= render partial: 'errors', locals: {vhub: @virtual_hub} %>
  <%= f.hidden_field :name %>
  <div><%= f.submit 'Create', class: 'btn btn-info' %></div>
<% end %>

app/views/virtual_hubs/edit.html.erb
<%= form_for(@vhub, url: update_vhub_path) do |f| %>
  <%= render partial: 'errors', locals: {vhub: @vhub} %>
  <%= f.label :description %>
  <%= f.text_area :description %><br/>
  <%= f.label :background %><br/>
  <%= f.file_field :background %>
  <%= f.label :avatar %><br/>
  <%= f.file_field :avatar %>
  <div>
    <%= f.submit 'Update', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/virtual_hubs/show.html.erb
<% if @vhub.nil? %>
  <div class="well">
	  <h1>the [ <%= @virtual_hub.name %> ] virtual hub does not exist yet.<h1>
		<h2>want to create it?</h2>
	</div>
	<%= render 'form' %>
<% else %>

  <% if @background.exists? %>
  <style>
    body {
	    background: url("<%= @background.url %>") no-repeat center center fixed;
	    -webkit-background-size: cover;
	    -moz-background-size: cover;
	    -o-background-size: cover;
	    background-size: cover;
    }
  </style>
  <% end %>

	<%= render partial: 'layouts/header', locals: {name: @vhub.name} %>
	
	<div class="row">
		<div class="span8">
			<%= render partial: 'layouts/posts', locals: {posts: @posts, post: @hub_post, controller: 'hub_posts'}%>
		</div>

		<div class="span4">
	    <div class="well">
		    <% if @avatar.exists? %>
	        <%= image_tag @avatar.url(:default) %>
	      <% else %>
	        <%= image_tag 'tiles/hippo.png' %>
	      <% end %>
	    </div>

	    <div class="well">
	      <%= @vhub.description %>
	    </div>
	
			<%= link_to 'Edit Virtual Hub', edit_vhub_path, class: 'btn btn-info' %>
		</div>
	</div>
	<% end %>