config/routes.rb
class Subdomain
  def self.matches?(request)
    return false unless (request.subdomain.present? && request.subdomain != "www")
    return false unless request.subdomain.size.between?(1,20)    
    return true
  end
end

Belloh::Application.routes.draw do

	constraints(Subdomain) do
	  get '/', to: 'virtual_hubs#show'
	  get 'edit', to: 'virtual_hubs#edit', as: 'edit_vhub'
	  patch 'update', to: 'virtual_hubs#update', as: 'update_vhub'
	  get 'sync', to: 'hub_posts#sync'
	end

  root 'welcome#show'

  get "user/:id", to: "users#show", as: "user"
  resources :hub_posts, only: [:index,:create]
  resources :virtual_hubs, only: [:create]

  resources :posts, only: [:index,:create]
  get 'sync', to: 'posts#sync'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'about', to: "information#about"
  get 'help', to: "information#help"
  get 'terms', to: "information#terms"
  get 'privacy', to: "information#privacy"
  get 'hubs', to: "information#hubs"
  get 'usage', to: "information#usage"

  

end

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= bootstrap_alert_type(name) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
  </div>
<% end %>

<script>
$(function(){
	setTimeout(function() {
    $('.alert').fadeTo(500, 0).slideUp(500, function(){
      $(this).remove(); 
    });
	}, 2000);
});
</script>

app/views/layouts/_header.html.erb
<div class="row-fluid">
	<div id="header" class="span10">
		<div id="belloh">
			<span><%= name %></span>
			<div id="wave">
				<span class="smallb">)</span>
				<span class="mediumb">)</span>
				<span class="largeb">)</span>
			</div>
		</div>
	</div>
	<div class="span2 well">
		<% if user_signed_in? %>
		  Signed in as: <%= link_to current_user.username, current_user %><br/>
	    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
	  <% else %>
	    <%= link_to "Sign In", new_user_session_path %>
	  <% end %>
	</div>
</div>

app/views/layouts/_posts.html.erb
<div id="posts-header" class="well">
	<div id="new_post_box" mood="<%= post.mood %>">
	  <%= render partial: 'posts/form', locals: {post: post} %>
  </div>
</div>

<div id="posts" class="well">
  <div id="filter-bar">
	  <%= form_tag({controller: controller, action: 'index'}, method: :get, id: 'filter-form', remote: true) do %>
	    <%= search_field_tag 'filter', nil, placeholder: t(:filter_placeholder) %>
	    <span id="ranges" style="<%= 'display: none' if  @range.nil? %>">
        <%= render partial: 'welcome/ranges', locals: {range: session[:range]} %>
			</span>
	  <% end %>
  </div>
  <div id="post-list">
	  <%= render partial: 'posts/list', locals: {posts: posts} %>
	</div>
	<div id="next-page">
		<%= link_to_next_page posts, 'Load more posts', remote: true, :params => {controller: controller, action: 'index'} %>
	</div>
</div>

<script>
$(function(){
	
	$('#filter').on('input',function(){
		$('#filter-form').submit();
	});
	
	updatePosts();
});

function updatePosts () {
  setTimeout(function(){
	  $.getScript("/sync.js");
		updatePosts();
	}, 10000);
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Belloh</title>
  <%= stylesheet_link_tag    "application" %>

  <meta content="belloh, locationable, locationable message, location-based, messaging, twitter challenger, instant message, pitch, local business, deal, sale, discount, coupon, promotion, daily deal, save, garage sale, yard sale, social deals, local, texting, special, on-map text, text messaging, chat, rant, praise, just saying, free speech, candid feedback, anonymous text messages" name="keywords">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--<meta name="viewport" content="initial-scale=1.0, user-scalable=no">-->
  <meta charset="utf-8">

	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places,visualization"></script>

	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container" id="content">
		<div id="alerts">
      <%= render 'layouts/alerts' %>
	  </div>
	  <%= yield %>
	</div>

	<div class="footer">
	  <div class="footer-left">
	    <span><%= link_to t(:about), about_path%></span>
	    <span><%= link_to t(:help), help_path%></span>
	    <span><%= link_to t(:terms), terms_path%></span>
	    <span><%= link_to t(:privacy), privacy_path%></span>
	    <span><%= link_to t(:hubs), hubs_path %></span>
	    <span><%= link_to t(:usage), usage_path%></span>
	    <span><%= link_to t(:blog), "http://belloh.blogspot.com" %></span>
	    <span><%= link_to "Twitter", "https://twitter.com/@bellohworld" %></span>
	  </div>

	  <div class="footer-right">
	    <span class="copyright-symbol">&copy;</span> 2013 Belloh.com.
	  </div>
	</div>

</body>

</html>